### ISSUE TITLE
GUI should show the version number and icons for buttons

### ISSUE THREAD

**Issue by lwbt** [mKenfenheuer/steam-deck-windows-usermode-driver#15] opened 2022-06-09 13:38 UTC
The GUI looks great!

Putting the version number in the log or somewhere else would help with bug reports I guess. I checked the version number of the executable (1.0) and under installed software (1.3 or 0.1.3, can't exactly remember) both were different to the version number I downloaded from the releases page. Putting the version number in the filename of the download would also be helpful I guess.

I'm still struggling to differentiate some buttons. A, B, X, RT are mostly self explanatory, but for others icons in the button mapping would help so you know what the button with the overlapping windows is. Looks like Microsoft has a font for that (https://support.xbox.com/en-US/help/hardware-network/controller/xbox-one-wireless-controller), not sure if you can use that or Font Awesome or something else appropriate.

**Comment by Dre2timez** [comment] 2022-06-09 21:45
Hey, does your config changed inputs work or do they also revert back after reopening the program? I opened a now closed issue report but the prob still remains.

**Comment by mKenfenheuer** [comment] 2022-06-10 10:51
> Hey, does your config changed inputs work or do they also revert back after reopening the program? I opened a now closed issue report but the prob still remains.

have a look at  #14. Might be the cause for that. Does the default profile work?
Also are you on release 2.0+?

**Comment by mKenfenheuer** [comment] 2022-06-10 10:52
> The GUI looks great!
> 
> Putting the version number in the log or somewhere else would help with bug reports I guess. I checked the version number of the executable (1.0) and under installed software (1.3 or 0.1.3, can't exactly remember) both were different to the version number I downloaded from the releases page. Putting the version number in the filename of the download would also be helpful I guess.
> 
> I'm still struggling to differentiate some buttons. A, B, X, RT are mostly self explanatory, but for others icons in the button mapping would help so you know what the button with the overlapping windows is. Looks like Microsoft has a font for that (https://support.xbox.com/en-US/help/hardware-network/controller/xbox-one-wireless-controller), not sure if you can use that or Font Awesome or something else appropriate.

Thats a good hint, will have a look at this, thanks!

**Comment by mKenfenheuer** [comment] 2022-06-10 17:41
Resolved in v0.2.3

https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/releases/tag/v0.2.3

**Closed by mKenfenheuer** 2022-06-10 17:41 UTC
