### ISSUE TITLE
[BUG] Latest version crashes randomly and shuts down

### ISSUE THREAD

**Issue by TankZealot** [mKenfenheuer/steam-deck-windows-usermode-driver#27] opened 2022-06-27 12:28 UTC
**Describe the bug**
Hi!
I've been using 0.2.4 for a while and it has worked great! Tried the new beta and it also works great! However, the program sometimes crashes randomly. I tried reinstall everything and it still crashes. Went back to 0.2.4 and works without issue, but now I kinda miss the keyboard input.

**To Reproduce**
1. Just opening the program and then it will crash at random.

**Screenshots**
![IMG_20220627_142329](https://user-images.githubusercontent.com/107768294/175941534-a6307e73-9adb-4841-8b58-355d1195ad34.jpg)

**Debug information**
New Beta

**Additional context**

**Comment by TankZealot** [comment] 2022-06-27 12:32
[SWICD_Support_637919294833284682.zip](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/files/8991953/SWICD_Support_637919294833284682.zip)

**Comment by DocMAX** [comment] 2022-07-10 08:09
I can confirm that. Randomly the app closes and the joystick is gone.

**Comment by mKenfenheuer** [comment] 2022-07-10 10:41
Hi, thank you for reporting!
Looks like the driver is trying to write to the log file but ist somehow getting blocked by itself.

```
[27/06/2022 14:23:23][Critical]: System.IO.IOException: The process cannot access the file 'C:\Users\TommySteamDeck\Documents\SWICD\driver_log.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```

I suspect this is due to the debug output of the button states, can you confirm this happens if you are heavily pressing buttons or pressing some simultaneously? What if you start the driver and do not touch any buttons? Does it crash too?

**Comment by mKenfenheuer** [comment] 2022-07-10 14:19
Possibly fixed with release [v0.2.5-beta2](https://github.com/mKenfenheuer/steam-deck-windows-usermode-driver/releases/tag/v0.2.5-beta2). Can you confirm?

**Comment by DocMAX** [comment] 2022-07-10 16:59
Looks stable now :-)

**Comment by TankZealot** [comment] 2022-07-10 18:41
Works much better for me too! Thank you for updating.

**Closed** 2022-07-10 20:25 UTC
Labels: bug
